name: gnome-nibbles
adopt-info: gnome-nibbles
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /usr/share/gnome-nibbles:
    bind: $SNAP/usr/share/gnome-nibbles

slots:
  # for GtkApplication registration
  gnome-nibbles:
    interface: dbus
    bus: session
    name: org.gnome.Nibbles

apps:
  gnome-nibbles:
    extensions: [gnome]
    command: usr/bin/gnome-nibbles
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.Nibbles.desktop
    common-id: org.gnome.Nibbles.desktop
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  gnome-nibbles:
    source: https://gitlab.gnome.org/GNOME/gnome-nibbles.git
    source-type: git
    source-tag: 3.38.2
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/org.gnome.Nibbles.appdata.xml]
    override-pull: |
      craftctl default
      for i in $CRAFT_PROJECT_DIR/patches/*.diff; do
        patch -p1 < $i
      done
